### ISSUE TITLE
GCC 8.2 generates warnings when compiling crt_abstractions.c

### ISSUE THREAD

**Issue by pboettch** [Azure/azure-c-shared-utility#174]
Using

    gcc (Debian 8.2.0-3) 8.2.0

I'm getting the following warnings (and thus errors due to `-Werror`) when compiling `crt_abstractions.c` and 

```Bash

azure-iot-sdk-c/c-utility/src/crt_abstractions.c: In function ‘strncpy_s’:
azure-iot-sdk-c/c-utility/src/crt_abstractions.c:163:19: error: ‘strncpy’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
             (void)strncpy(dst, src, srcLength);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
azure-iot-sdk-c/c-utility/src/crt_abstractions.c:132:28: note: length computed here
         size_t srcLength = strlen(src);
                            ^~~~~~~~~~~
azure-iot-sdk-c/c-utility/src/crt_abstractions.c:149:23: error: ‘strncpy’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
                 (void)strncpy(dst, src, srcLength);
                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
azure/azure-iot-sdk-c/c-utility/src/crt_abstractions.c:132:28: note: length computed here
         size_t srcLength = strlen(src);
                            ^~~~~~~~~~~
```

GCC seems unable to determine that srcLength has been "corrected" to not exceed destlen. Maybe `memcpy()` should be used. NUL-termination is done manually right after.

**Comment by pboettch** [comment]
`strncpy()` also sets the NUL-char. But the way it is used in this code is that the calculated length of the dest-string will always be just one-too-short for the NUL-char. Hence the manual termination in the code.

**Comment by Morozov-5F** [comment]
@pboettch Extracted from man page: 
```
The stpncpy() and strncpy() functions copy at most len characters from
src into dst.  If src is less than len characters long, the remainder of
dst is filled with `\0' characters.  Otherwise, dst is not terminated.
```

**Comment by Morozov-5F** [comment]
@pboettch You're right, this doesn't help at all.

**Comment by dcristoloveanu** [comment]
"But I'm sure there was a good initial reason for them to chose strncpy. "
Unfortunately, not necessarily :-). You are right, this should have been a mempcy.

We did have a pass of replacing all these occurrences with memcpy, since the usual pattern is to get the size of the string, allocate memory for it and then copy. So in almost all cases we technically do not need strncpy, but a memcpy + appropriate levels of unit tests.

Btw, that strncpy_s function was written in the very early stages of the project a couple of years ago. At that time it was not even named IoTHub yet :-).
It is only used in serializer, the bulk of IoTHub client does not use it.

So, this should be just replaced with a memcpy and your issue should be solved.
I think you should simply PR it and I can review it for you and someone from the team will merge it.

Cheers!
/Dan

**Comment by az-iot-builder-01** [comment]
@pboettch, @Morozov-5F, @dcristoloveanu, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
