### ISSUE TITLE
malloc(0) can return NULL or valid pointer

### ISSUE THREAD

**Issue by yaweiw** [Azure/azure-c-shared-utility#18]
https://github.com/arduino-libraries/AzureIoTHub/pull/25

This could lead to incorrect/inconsistent behavior on different boards.

**Comment by dcristoloveanu** [comment]
Hi @yaweiw 

I think what should happen here in BUFFER_Create is that we should succeed even if the size is 0. Then in cases where the code that uses BUFFER does not want to care what the size of the buffer being created is, the BUFFER_Create calls succeed even if the size is 0.

In order to streamline contributing the change:

- Let's have the PR against develop
- Please make sure to update the .md requirement doc for buffer in the devdoc folder in order to state that BUFFER_Create with 0 size shall succeed
- Please add a unit test in the BUFFER test suite under tests.

I'll look for your PR so I can review it in a timely fashion.

Thanks for contributing,
/Dan

**Comment by yaweiw** [comment]
@dcristoloveanu , ok

**Comment by dcristoloveanu** [comment]
This fix been merged.
