### ISSUE TITLE
Number of logging levels should be increased

### ISSUE THREAD

**Issue by hunterwerlla** [Azure/azure-c-shared-utility#227]
Hi, I work on another team in Microsoft that is using the azure-c-shared-utility and one of the issues we are having is the lack of logging levels. Since there is only info/error it's hard to justify adding messages that are useful for debugging as to not overwhelm the log.

We would really appreciate officially supported additional levels of logging, thanks!

**Comment by massand** [comment]
@hunterwerlla - please detail your specific requirements for this request. We would potentially roll this item in with other logging improvements we would like to make across the SDK. Getting these requirements will help us figure out better overall design for logging in the next few releases. Thanks!

- Is there Critical, Warning, Info, Debug levels that would help you? 
- If there is a lot of logging expected to be added, (I assume so since you are looking for categorizing them), do you expect post-processing the log information off the device or are you piping the logs in real-time?

**Comment by hunterwerlla** [comment]
Those levels of logging would help us, at the very least we would like a Debug. We package up logs and look at them, but we are not doing any large scale log parsing.
