### ISSUE TITLE
Fails to build on Linux

### ISSUE THREAD

**Issue by koalo** [Azure/azure-c-shared-utility#251]
Since 3abd81c06fb it is no longer possible to build on Linux since the following expression is invalid if `${CMAKE_SYSTEM_VERSION}` is not set.

https://github.com/Azure/azure-c-shared-utility/blob/1d622902d7842f94193fc394987f2b4e978bb700/CMakeLists.txt#L267

**Comment by YoDaMa** [comment]
@koalo according to the CMake documentation ([here](https://cmake.org/cmake/help/v3.13/variable/CMAKE_SYSTEM_VERSION.html)), CMAKE_SYSTEM_VERSION is set to the version of the operating system for which cmake is to build. This by default is set to the same value as the CMAKE_HOST_SYSTEM_VERSION variable so that the build targets the host system version. 

However if you are cross compiling and the CMAKE_SYSTEM_NAME variable is set explicitly to enable cross compiling then the value of CMAKE_SYSTEM_VERSION must also be set explicitly to specify the target system version.

**Comment by az-iot-builder-01** [comment]
@koalo, @YoDaMa, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
