### ISSUE TITLE
Failed in building azure-c-shared-utility on OSX.

### ISSUE THREAD

**Issue by jiangzhibin** [Azure/azure-c-shared-utility#28]
[ 22%] Linking C executable umock_c_ut_exe
[ 22%] Built target umock_c_ut_exe
[ 22%] Linking CXX static library libmicromock_ctest.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmicromock_ctest.a(micromocktestmutex.cpp.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmicromock_ctest.a(micromocktestmutex.cpp.o) has no symbols
[ 22%] Built target micromock_ctest
make: **\* [all] Error 2
// ------------------------------------------------------------------------------
I built it step by step:
1.Clone **azure-c-shared-utility**,and checked out the develop branch
2. Create a folder called _cmake_ under _azure-c-shared-utility_
3.Switch to the _cmake_ folder and run "cmake .."
4.switch to the "/azure-c-shared-utility/build_all/linux/"  and run "sudo ./build.sh"
and then I failed in building the azure-c-shared-utility.
Any help would be appreciated.

**Comment by markrad** [comment]
Hi @jiangzhibin,

I'm not exactly sure what caused your particular issue. I have managed to build the SDK on OSX albeit without the unit tests. You will need to install brew if you have not already done so.

With brew you will need to install gcc, openssl, pkgconfig, ossp-uuid and valgrind. Once you have those installed I refer you to this pull request: https://github.com/Azure/azure-iot-sdk-c/pull/5/files. This was recently submitted and I pretty much replicated the changes made. Reviewing each file in turn:

**CMakeLists.txt** - I included all of these changes

**build_all/osx/build.sh** - I created this new file in the new directory. However there are a couple of bugs in it. The call to _sysctl hw.ncpu_ (line 136) needs to be piped to _cut -d ' ' -f 2_, The call to _sysctl hw.memsize_ also needs the same treatment. It can also be directly assigned to _VSPACE_ and the calculations on _MEMAR_ can be removed (lines 143 and 144). This is due to a different output format of the command compared to the original Linux version of the script. I also modified the compiler used to build the SDK by passing the options _-D CMAKE_C_COMPILER=x86_64-apple-darwin15.6.0-gcc-6_ and _-D CMAKE_CXX_COMPILER=x86_64-apple-darwin15.6.0-g++-6_

**build_all/osx/setup.sh** - I did not bother with this script since I had already used brew to pull in the dependencies. 

**iothub_client/tests/iothubtransporthttp_ut/iothubtransporthttp_ut.cpp** - I ignored all of these changes. The reason being that this pull request was set up to use the default compiler, clang. This compiler is a little more picky than gcc. I chose to build the SDK with gcc so I did not need these changes.

**iothub_service_client/samples/iothub_devicemethod_sample/CMakeLists.txt** - I applied these changes.

**iothub_service_client/samples/iothub_messaging_sample/CMakeLists.txt** - I applied these changes.

Once these changes were complete I run _build.sh_ from the new _osx_ directory. I used the argument _--skip-unittests_ because at this point I have not managed to get the unit tests to build.l

I'm anticipating better support for building under OSX. Let me know if you have further problems.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
Hi @jiangzhibin,

Do you have any further problems regarding the build on OSX? If I don't hear from you I will consider this resolved and close the issue. 

Thank you.

_Mark Radbourne MSFT_
