### ISSUE TITLE
"Operating mode must not be set while SNTP client is running" if SNTP has already been initialized

### ISSUE THREAD

**Issue by dmitriychernenko** [Azure/azure-c-shared-utility#294]
Hi,
I explicitly initialize SNTP in my project (my existing code needs time).
I've tried to use Azure IoT SDK to talk to Azure IoT hub.
App crashes with following error message: "Operating mode must not be set while SNTP client is running". I believe this caused by this code https://github.com/Azure/azure-c-shared-utility/blob/694116b047f86bac28375d571e016a01d90eaa1b/pal/lwip/sntp_lwip.c#L39

**Comment by kbeaugrand** [comment]
Hi Dimitry, 

Did you find any solution to this problem? I'm facing the same issue while connecting a device throught a transparent gatewa that is not providing public internet routing. 
Since no internet is available on device, it fails to get NTP from pool.npt... 

So I configured sntp to get time from my gateway on my device code like this:
```c
    sntp_setoperatingmode(SNTP_OPMODE_POLL);
    sntp_setservername(0, "192.168.10.1");
    sntp_init();

```
Hope tha this case is possible...

**Comment by Leadrive** [comment]
before sntp_setoperatingmode
add these codes:
if ( sntp_enabled() ) {
sntp_stop();
}

**Comment by ewertons** [comment]
Closing as resolved given the last comment from Leadrive.
Thanks,
Azure IoT SDKs Team
