### ISSUE TITLE
How to gracefully use xio_dowork()?

### ISSUE THREAD

**Issue by Kevin0626** [Azure/azure-c-shared-utility#305]
Hi,
I have some questions about the sample "socketio_connect". It looks the xio_dowork() is doing nonblocking operations for sending queued message and receiving from the socket. The sample below will cause 100% utilization of CPU?? 
		    unsigned char done = 0;
                    while (!done)
                    {
                        xio_dowork(socketio);
                    }
Adding some usleep() call may avoid the CPU utilization issue, but it seems hard to set appropriate length of sleeping duration. 

should we make it blocking call with a timeout parameter? or provide some API for doing blocking wait on the socket event like select?

Another question is about calling send api from another thread. It seems the link for sending queue is not thread protected. 

Overall, it is quite difficult to me to configure out a programming pattern with the API design for the socket. I am grateful for any guidance here.

**Comment by jspaith** [comment]
Sorry that this slipped by us so long.

The short answer to your question is you've completely read the API correctly but this pattern is too fundamental for us to change to be select()|epoll|Event|... based.

===
Since you spent time researching this though you should get a more detailed answer.

Your reading of the API is correct.  If you didn't put in a sleep() between xio_dowork() invocations, you'd peg the CPU.  If you look at the examples of the IoT Device SDK that builds on top of all this (through abstractions of course), [here](https://github.com/Azure/azure-iot-sdk-c/blob/d1de35c54f6d50fb921017465379f893862bbd5a/iothub_client/samples/iothub_ll_telemetry_sample/iothub_ll_telemetry_sample.c#L180), you'll see that there's a sleep after the "DoWork()" to avoid this.

I've looked into the `select()` model you propose around a poll with a timeout.  This would be a fundamental change that would impact almost everything on top of us and borderline require a rewrite.  So it's not something we're going to change.

The way we're addressing the IoT based SDK's going forward is different, at least on truly embedded devices like bare metal, Azure RTOS, FreeRTOS, VXworks, etc.  I understand that the c-utility can be used independently of the IoT, but c-utility was written first as an IoT utility by the same team who does IoT C libraries.  *Rest of this mail is pretty IoT centric; the Windows|Linux that's based on C is still c-utility which as I said we can't really change.*

We're not going to try to do a common denominator where we guess the architceture - spinning|poll-based|etc - that you're using.  Instead we provide a lot more primitive building blocks that you can compose yourself so you can use the best possible design for your scenario.  And for targeted embedded OS's we'll have middlewares that are per-OS targeted to make it easier, but since we building for a specific OS from the ground up we can tightly optimize for their scenarios.

Specific examples:
- The [embedded SDK](https://github.com/Azure/azure-sdk-for-c), which is for barebones systems using IoT and that other consumers use.  There's Windows|Linux samples to show bring up along with a few platformrs, including a vxworks sample from Windriver that's in PR presently.
- [Azure RTOS middleware](https://github.com/azure-rtos/netxduo/tree/master/addons/azure_iot)
- [FreeRTOS middleware](https://github.com/Azure/azure-iot-middleware-freertos) for FreeRTOS
