### ISSUE TITLE
socketio_berkeley.c: non-blocking recv() returning 0 should not be treated as error

### ISSUE THREAD

**Issue by otg-abatec** [Azure/azure-c-shared-utility#330]
socketio_berkley.c is using non-blocking sockets in lookup_address_and_initiate_socket_connection():

 https://github.com/Azure/azure-c-shared-utility/blob/a9ca2c70c288761bb01c9578846417f0d76fde27/adapters/socketio_berkeley.c#L313

in a non-blocking scenario a recv() returning 0 is considered desired behaviour. Nevertheless socketio_dowork() is indicating an error in this case.

https://github.com/Azure/azure-c-shared-utility/blob/a9ca2c70c288761bb01c9578846417f0d76fde27/adapters/socketio_berkeley.c#L991-L995

On our platform STM32/FreeRTOS/LWIP/mbedTLS this breaks the communication.

**Comment by markrad** [comment]
I took a look at this. It works on Linux since the Berkeley socket library does not  return zero on that platform to indicate there is no data. If there is no data it will set -1 and errno to EAGAIN. Since I don't have your particular hardware I can only assume that the socket library is behaving differently and returning zero when there is no data to receive. This does not seem to be consistent with typical implementations of the Berkeley socket library since a zero return code is used to indicate that the peer has gracefully closed the connection. 

Modifying it in the way you are suggesting would effectively break Linux implementations since we would not be able to detect the closed connection. Perhaps, instead, you should raise the issue of an inconsistent implementation with the owner of the Berkeley socket library you are using.

_Mark Radbourne Azure IoT Support_

**Comment by otg-abatec** [comment]
thanks for reviewing this issue - I must admit, that I was a bit in a hury when debugging the adapter code. Recv() returuning -1 and errno = EAGIN in non-blocking mode should be correct. I will have a look at the LWIP socket code to see in witch cases exactly 0 was returned ... so disabling indicate_error for received = 0 did solve my problem in practice but there is something else going on which deserves attenation.

**Comment by otg-abatec** [comment]
I had a second look on this issue - i have to say that i made a mistake - while testing this module we had the lwip-thread running at a lower priority than our communication task - this lead to some race conditions where recv() was queried in non-blocking mode while the connection was not even established.

**Comment by az-iot-builder-01** [comment]
@otg-abatec, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
