### ISSUE TITLE
Missing C-make & Compiling flags for mbedtls

### ISSUE THREAD

**Issue by simonemarra** [Azure/azure-c-shared-utility#51]
Hi,
I'm using the tlsio_mbedtls.c file provided on your the azure-c-shared-utility repo on my embedded project.
I'm guessing if there is a rapid way to use it with Visual studio or Linux too (some like the -Duse flags present for wolfssl, openssl and so on...).

I'm experiencing some problems on Disconnection/Connection behaviour using my (custom) embedded device.
Before to raise some other questions/tips I need to have a feedback using also a PC among with your socketio_xxx files.

**Comment by anporumb** [comment]
Hello @simonemarra ,

There seem to be 3 issues in your post
1) cmake support for mbedtls adapter - we do not have time to look at this enhancement - feel free to submit a PR to add it.
2) disconnect/connections issues - can you provide more details please? Otherwise we don't know.
3) Can you please clarify the issue regarding/using on the PC?

Best Regards,
Andrei Porumb
