### ISSUE TITLE
TLS Session Ticket support

### ISSUE THREAD

**Issue by simonemarra** [Azure/azure-c-shared-utility#64]
Hi!
I'm working on a mbedtls-based C device firmware (using MQTT protocol). Since our devices uses GPRS/3G connectivity, we need to add SSL/TLS session ticketing support to restore TLS session and avoid lots of data in case of network connection failures.

I'm testing the SSL Session Ticketing with IOTHUB servers without success. I'm using both my mbedtls-based device and openssl with my PC. In both cases Azure servers seems to ignore the SSL session resume feature.

The openssl commands i used to test it are:
`
openssl s_client -connect myIothubInstance:8883 -reconnect
`

or

`
openssl s_client -connect myIothubInstance:8883 -sess_out ./azure_sess_ticket
`
`
openssl s_client -connect myIothubInstance:8883 -sess_in ./azure_sess_ticket
`

Using my own nodejs mqtt server I have no problems at all.

- Is it a (wanted) limitation included by Microsoft?
- Can you consider to support the SSL Session Ticket feature so we can reduce our data usage?
- Am I doing something wrong with TLS tickets?

**Comment by dcristoloveanu** [comment]
Hi @simonemarra,

I do not think you are doing anything wrong, we currently do not support this, so it is a limitation for the SDKs.
We will consider this for the future, once we have more information on when this would be taken we'll update the thread.

Thanks,
/Dan

**Comment by simonemarra** [comment]
Ok,
Do you have any idea of the timings on such feature to be supported?

**Comment by jspaith** [comment]
@simonemarra - this is on our radar, but it's not going to be in the next few months.

I was going to suggest you create an item on user voice because this will require both service & SDK support, but it looks like [you've already done so](https://feedback.azure.com/forums/321918-azure-iot/suggestions/31456585-add-tls-session-ticket-support-to-reduce-data-exch).

Since the user voice is better place to track given SDK/service nature of this, I'm going to close out this issue on GitHub.  Sorry we don't have a better answer for you at present.
